// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kljkfcsucfeuljsvokrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsamtmY3N1Y2ZldWxqc3Zva3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjEwMzgsImV4cCI6MjA2MjY5NzAzOH0.x6N18y3a4Dskis_1QR_8-N27iJ73bgytEYd_gdmaHxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);